language: bash

env:
  - DOCKER_COMPOSE_VERSION="1.25.4" SLEEP_TIME=240 PORT=8085

sudo: required

cache:
  directories:
    - .git/lfs
git:
  lfs_skip_smudge: true

python:
  - '3.5'

services:
  - docker

install :

  - sudo curl -L "https://github.com/docker/compose/releases/download/1.25.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose  &&  sudo chmod +x /usr/local/bin/docker-compose
  - sed -i 's/[0-9]*[1-9][0-9]*:80/'${PORT}':80/g' docker-compose.yml
  - docker-compose build
  - docker-compose up -d
  - sleep ${SLEEP_TIME}

script:
  - sudo bash check_config.sh
  - sudo bash check_poc.sh
  - cat docker-compose.yml
  - curl -vv -L http://127.0.0.1:${PORT}
  # - docker exec -it web-app /bin/sh
  # - rm /var/www/html/install.php
  # - exit