name: DVE Test
on: [push, pull_request]
jobs: 
  deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Build Images And Backup
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: shawnsky/powerdns
        path: .
        tags: latest

